### ISSUE TITLE
Feature Request: Taskbar - reorder, hide labels

### ISSUE THREAD

**Issue by veremenko-y** [dremin/cairoshell#4]
As a developer I have bunch of apps open and the same time. It would be nice to be able to hide labels and reorder applications.
![image](https://cloud.githubusercontent.com/assets/4127660/25757093/6c9d6374-3186-11e7-9bde-488c10f8290d.png)

**Comment by dremin** [comment]
The taskbar now shrinks labels to accommodate many more items.
Taskbar buttons can be ordered the same way as the Programs menu by using the App Grabber categorization features.
Quick Launch icons can be reordered by drag and drop.

Updates are available at this repository: https://github.com/cairoshell/cairoshell
