### ISSUE TITLE
Wrong path in AppGrabber on non-english Windows

### ISSUE THREAD

**Issue by erdnaxe** [dremin/cairoshell#8]
Hello,

Cairo AppGrabber doesn't work on French Windows:
- Cairo is trying to access "C:\Users\***\AppData\Roaming\Microsoft\Windows\Start Menu\Programmes",
- But programs are in "C:\Users\***\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"

Regards,

> Message: L'accès au chemin d'accès 'C:\Users\Alexandre\AppData\Roaming\Microsoft\Windows\Start Menu\Programmes' est refusé.
> Target Site: Void WinIOError(Int32, System.String)
> Version: 0.2.6443.5860
> 
>    à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    à System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
>    à System.IO.FileSystemEnumerableIterator`1.MoveNext()
>    à CairoDesktop.AppGrabber.AppGrabber.generateAppList(String directory)
>    à CairoDesktop.AppGrabber.AppGrabber.GetApps()
>    à CairoDesktop.AppGrabber.AppGrabber.get_ProgramList()
>    à CairoDesktop.AppGrabber.AppGrabberUI.Window_ContentRendered(Object sender, EventArgs e)
>    à System.Windows.Window.OnContentRendered(EventArgs e)
>    à System.Windows.Window.<PostContentRendered>b__198_0(Object unused)
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by dremin** [comment]
This should be working now in the latest release. Thanks for reporting!
